apiVersion: apps/v1
kind: Deployment
metadata:
  name: pose-hackathon-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pose-hackathon-23
  template:
    metadata:
      labels:
        app: pose-hackathon-23
    spec:
      containers:
        - name: pose-hackathon-23
          image: ghcr.io/uvinw/pose-hack-23:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pose-hackathon-23-service
spec:
  selector:
    app: pose-hackathon-23
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pose-hackathon-23-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: pose.vivira.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pose-hackathon-23-service
                port:
                  number: 80
